name: update-dependencies-job
on:
  repository_dispatch:
    types: [update-dependencies-command]
  schedule:
    - cron:  '0 0 * * 0'  # every Sunday midnight
  push: {}
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update deps
        run: |
          make vendor

      - name: See status
        run: |
          git status

      #- name: Hello world action step
      #  uses: ./actions/update-dependencies # Uses an action in the root directory
      #  id: hello
      #  with:
      #    who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step

      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
